
package delme2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4-jbossorg-1
 * 2018-07-23T17:42:49.583+03:00
 * Generated source version: 3.2.4-jbossorg-1
 */

@WebFault(name = "MyServiceFault", targetNamespace = "http://pnr.indexbg.bg/")
public class WSFault extends Exception {

    private delme2.MyServiceFault myServiceFault;

    public WSFault() {
        super();
    }

    public WSFault(String message) {
        super(message);
    }

    public WSFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WSFault(String message, delme2.MyServiceFault myServiceFault) {
        super(message);
        this.myServiceFault = myServiceFault;
    }

    public WSFault(String message, delme2.MyServiceFault myServiceFault, java.lang.Throwable cause) {
        super(message, cause);
        this.myServiceFault = myServiceFault;
    }

    public delme2.MyServiceFault getFaultInfo() {
        return this.myServiceFault;
    }
}
