package delme2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4-jbossorg-1
 * 2018-07-23T17:42:49.608+03:00
 * Generated source version: 3.2.4-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://ssp.indexbg.bg/", name = "WSSystemData")
@XmlSeeAlso({ObjectFactory.class})
public interface WSSystemData {

    @WebMethod
    @RequestWrapper(localName = "getMainAisId", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetMainAisId")
    @ResponseWrapper(localName = "getMainAisIdResponse", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetMainAisIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Long getMainAisId() throws WSFault;

    @WebMethod
    @RequestWrapper(localName = "getFullClassif", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetFullClassif")
    @ResponseWrapper(localName = "getFullClassifResponse", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetFullClassifResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<delme2.SystemClassif> getFullClassif(
        @WebParam(name = "codeClassif", targetNamespace = "")
        java.lang.Long codeClassif,
        @WebParam(name = "lang", targetNamespace = "")
        java.lang.Long lang
    ) throws WSFault;

    @WebMethod(action = "urn:Version")
    @RequestWrapper(localName = "version", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.VersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String version();

    @WebMethod
    @RequestWrapper(localName = "getFullList", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetFullList")
    @ResponseWrapper(localName = "getFullListResponse", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetFullListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<delme2.SyslogicListEntity> getFullList(
        @WebParam(name = "idList", targetNamespace = "")
        java.lang.Long idList
    ) throws WSFault;

    @WebMethod
    @RequestWrapper(localName = "getOpisClassif", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetOpisClassif")
    @ResponseWrapper(localName = "getOpisClassifResponse", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetOpisClassifResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<delme2.SystemClassifOpis> getOpisClassif(
        @WebParam(name = "lang", targetNamespace = "")
        java.lang.Long lang
    ) throws WSFault;

    @WebMethod
    @RequestWrapper(localName = "getModelData", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetModelData")
    @ResponseWrapper(localName = "getModelDataResponse", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetModelDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<delme2.AnyTypeArray> getModelData(
        @WebParam(name = "tableName", targetNamespace = "")
        java.lang.String tableName,
        @WebParam(name = "lang", targetNamespace = "")
        java.lang.Long lang,
        @WebParam(name = "aisId", targetNamespace = "")
        java.lang.Long aisId
    ) throws WSFault;

    @WebMethod
    @RequestWrapper(localName = "getOpisList", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetOpisList")
    @ResponseWrapper(localName = "getOpisListResponse", targetNamespace = "http://ssp.indexbg.bg/", className = "delme2.GetOpisListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<delme2.SyslogicListOpisEntity> getOpisList(
        @WebParam(name = "lang", targetNamespace = "")
        java.lang.Long lang
    ) throws WSFault;
}
